### ISSUE TITLE
Unavailable for R 3.3.2

### ISSUE THREAD

**Issue by veleritas** [dhimmel/hetior#1]
Hetior is currently not able to be installed via the usual method (`install.packages("hetior")`) from the R terminal for R version 3.3.2.

The error message I get is:

```
Warning message:
package ‘hetior’ is not available (for R version 3.3.2)
```

**Comment by dhimmel** [comment]
@veleritas, I haven't uploaded `hetior` to CRAN and I wasn't really planning to, but I can if that would help you.

However, it may just be easier to use:

```R
devtools::install_github(repo='dhimmel/hetior', ref='1bdeadad00b4d70e753b20c3735847931c03161e')
```

The ref uses the git commit hash to add versioning. If you remove the `ref` argument, you'll get the latest version of `master`.

Does that work?

**Comment by veleritas** [comment]
Yep, works fine. Once a package has been submitted to CRAN, does it not get propagated to later R versions automatically?

**Comment by dhimmel** [comment]
> Once a package has been submitted to CRAN, does it not get propagated to later R versions automatically?

I believe it does. Just I never submitted `hetior` to CRAN, as I don't really see it as a cohesive general purpose package. Although it does have many useful functions, they're scattered in their domains.
